const SIGN_UP = {
  INIT: "SIGN_UP",
  SUCCESS: "SIGN_UP_SUCCESS",
  FAILURE: "SIGN_UP_FAILURE",
};

const LOGIN = {
  INIT: "LOGIN",
  SUCCESS: "LOGIN_SUCCESS",
  FAILURE: "LOGIN_FAILURE",
};

const VERIRIFCATION = {
  INIT: "VERIFICATION",
  SUCCESS: "VERIFICATION_SUCCESS",
  FAILURE: "VERIFICATION_FAILURE",
};

export { SIGN_UP, LOGIN, VERIRIFCATION };
