const SIGN_UP = {
  INIT: "SIGN_UP",
  SUCCESS: "SIGN_UP_SUCCESS",
  FAILURE: "SIGN_UP_FAILURE",
};

const LOGIN = {
  INIT: "LOGIN",
  SUCCESS: "LOGIN_SUCCESS",
  FAILURE: "LOGIN_FAILURE",
};

const VERIRIFCATION = {
  INIT: "VERIFICATION",
  SUCCESS: "VERIFICATION_SUCCESS",
  FAILURE: "VERIFICATION_FAILURE",
};

const RESEND_VERIFICATION = {
  INIT: "RESEND_VERIFICATION",
  SUCCESS: "RESEND_VERIFICATION_SUCCESS",
  FAILURE: "RESEND_VERIFICATION_FAILURE",
};

const TWO_FACTOR = {
  INIT: "TWO_FACTOR",
  SUCCESS: "TWO_FACTOR_SUCCESS",
  FAILURE: "TWO_FACTOR_FAILURE",
};

export { SIGN_UP, LOGIN, VERIRIFCATION, RESEND_VERIFICATION, TWO_FACTOR };
