const GET_ME = {
  INIT: "GET_ME",
  SUCCESS: "GET_ME_SUCCESS",
  FAILURE: "GET_ME_FAILURE",
};

const LOGOUT = {
  INIT: "LOGOUT",
  SUCCESS: "LOGOUT_SUCCESS",
  FAILURE: "LOGOUT_FAILURE",
};

export { GET_ME, LOGOUT };
