const GET_PROJECTS_LIST = "GET_PROJECTS_LIST";
const GET_PROJECTS_LIST_SUCCESS = "GET_PROJECTS_LIST_SUCCESS";
const GET_PROJECTS_LIST_FAILURE = "GET_PROJECTS_LIST_FAIURE";

export {
  GET_PROJECTS_LIST,
  GET_PROJECTS_LIST_SUCCESS,
  GET_PROJECTS_LIST_FAILURE,
};
