const GET_MANGA_LIST = "GET_MANGA_LIST";
const GET_MANGA_LIST_SUCCESS = "GET_MANGA_LIST_SUCCESS";
const GET_MANGA_LIST_FAILURE = "GET_MANGA_LIST_FAIURE";

export { GET_MANGA_LIST, GET_MANGA_LIST_SUCCESS, GET_MANGA_LIST_FAILURE };
