const GET_VIDEO_LIST = {
  INIT: "GET_VIDEO_LIST",
  SUCCESS: "GET_VIDEO_LIST_SUCCESS",
  FAILURE: "GET_VIDEO_LIST_FAILURE",
};

const GET_SINGLE_VIDEO = {
  INIT: "GET_SINGLE_VIDEO",
  SUCCESS: "GET_SINGLE_VIDEO_SUCCESS",
  FAILURE: "GET_SINGLE_VIDEO_FAILURE",
};

export { GET_VIDEO_LIST, GET_SINGLE_VIDEO };
